### ISSUE TITLE
Some NRIs are shown weirdly

### ISSUE THREAD

**Issue by iceblade112** [xtridence/TO-Toolbox#1]
This happens on the latest (stable/master branch) pushed version.

NRIs like `data/character/Trs001.nri`, `data/character/chr101.nri`, and `data/ui_nori/DummyBG.nri` show weird output.

These images were extracted without modification except for the conversion to PNGs:

![GM char (chr10*.nri)](https://cloud.githubusercontent.com/assets/1739197/9287334/b5afe544-42dd-11e5-9d41-9a1d9c579fbb.png)
![Transform (Trs00*.nri)](https://cloud.githubusercontent.com/assets/1739197/9287335/b5b2b35a-42dd-11e5-8981-211981d60518.png)
![DummyBG](https://cloud.githubusercontent.com/assets/1739197/9287336/b5b62bca-42dd-11e5-884e-5c4f6781764e.png)

**Comment by xtridence** [comment]
Thanks for reporting this issue.
A fix has been submitted: https://github.com/TricksterOnline/TO-Toolbox/commit/5f2bc42e29cc883c7e8c739d8388884f81943f16

**Comment by iceblade112** [comment]
Nice. There were a few NRIs that just couldn't be read too, but I'll check later.

**Comment by PyroSamurai** [comment]
xtridence please edit your commit message for https://github.com/TricksterOnline/TO-Toolbox/commit/5f2bc42e29cc883c7e8c739d8388884f81943f16 so that instead of "Fix" it says "Fix #1" which will automatically mark this issue as resolved.
