### ISSUE TITLE
Some NRIs can't be loaded (again)

### ISSUE THREAD

**Issue by iceblade112** [xtridence/TO-Toolbox#5]
If you select an image from the list, nothing happens. If you go to the Animations tab and select something, it'll say "Parameter is not valid."

Example NRI: data\npc\npc001.nri

(I think.)

**Comment by xtridence** [comment]
Issue reproduced (apparently malformed color table). I'll look at it in my free time.

**Comment by iceblade112** [comment]
Yay! And now I continue my search for broken NRIs...
