### ISSUE TITLE
Move tool over to Mono Framework

### ISSUE THREAD

**Issue by PyroSamurai** [xtridence/TO-Toolbox#6]
Not sure why I didn't think of this before (probably b/c I was hung up about it being in C# in first place).
Anyways, this is just a self-task issue so that I can mark it off when I'm done.

**_GOAL_**: _Move tool over to Mono Framework and fix anything that prevents me from doing so._

**Reason 1**: Because C# only works on Unix-like OSes via the Mono Framework.
**Reason 2**: This app doesn't work via wine, simply crashes on startup. So no other option than Mono.

**Comment by iceblade112** [comment]
What about waiting for a stable release of .NET Core 2 first?

**Comment by PyroSamurai** [comment]
Not worth it. My time is always in short supply, so waiting isn't exactly a favorable option. According to the [roadmap](https://github.com/dotnet/core/blob/master/roadmap.md), the stable version will be released this month anyways and a preview version already has.

This app is only suppose to be a prototype, long-term concerns are moot. It was always the plan between me and xTridence that once we had a workable program that we would rewrite it in C/C++. The prototype was simply written in C# because he said it was quicker for him. A common practice in development.

Regardless, he has apparently quit the project. So I must finish it now and, as you know, only Mono C# works on my OS.

So my process now is:  C# => Mono C# =/\\/=> C/C++. It's a little more complicated than that, but worry not, I will be including Windows support in the C/C++ code.

**Comment by PyroSamurai** [comment]
The code is far more compatible with Mono than I initially thought. It simply requires a extra library and the removal of an ancillary component which does an external performance check for fun.

Thus all the program needs is some install instructions (for ubuntu) which I will add. This prototype went beyond what I wanted to achieve which was a nori extracter (and packer - for brownie points). Thus I have little use for most of the code, especially the GUI code. Additionally the nori extraction code for this tool is still incomplete resulting in occasionally bitmap images that are a garble of black, pink, and white.

I will be creating a new repo for the C/C++ tool because of this and leaving this one alone after including the new install instructions. The new tool will take what insights about nori extraction we gained from this tool and applying it to new one without a GUI.

Optionally, I am willing to remove the nori code from this program and leave it as a libconfig editor as it seems that ended up being xTridence main passion for this app instead of the intended nori manipulator. That decision is up to the fans though. 

The new app will be more in line with this organization's goals of creating a Trickster Online clone with libre licensing. That goal has little use for maintaining the original cumbersome file formats. So other than maintaining this program's ability to compile, it is now deprecated.
